container:
    image: python
    cpu: 1
    memory: 500M

task:
    name: Validate Play Store and F-Droid descriptions
    play-stable-script: python3 assets/store_descriptions/generate_and_validate.py play
    play-beta-script: python3 assets/store_descriptions/generate_and_validate.py playBeta
    fdroid-stable-script: python3 assets/store_descriptions/generate_and_validate.py fdroid
    fdroid-beta-script: python3 assets/store_descriptions/generate_and_validate.py fdroidBeta
