linters:
    checkstyle:
        config: ./stickler/checkstyle.xml
    ktlint:
        android: true
        config: ./.editorconfig
        fixer: true
    yamllint:
        config: ./stickler/yamllint.yml
