files:
  - source: /mobile/src/main/res/values/strings.xml
    translation: /mobile/src/main/res/values-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        pt-BR: pt-rBR
  - source: /assets/store_descriptions/en-US/strings.xml
    translation: /assets/store_descriptions/%locale%/%original_file_name%
  - source: /mobile/src/beta/res/values/strings.xml
    translation: /mobile/src/beta/res/values-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        pt-BR: pt-rBR
  - source: /mobile/src/foss/res/values/strings.xml
    translation: /mobile/src/foss/res/values-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        pt-BR: pt-rBR
  - source: /mobile/src/full/res/values/strings.xml
    translation: /mobile/src/full/res/values-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        pt-BR: pt-rBR
