files:
  - source: /mobile/src/main/res/values/strings.xml
    translation: /mobile/src/main/res/values-%android_code%/%original_file_name%
  - source: /assets/store_descriptions/en-US/strings.sh 
    translation: /assets/store_descriptions/%locale_with_underscore%/%original_file_name%
