files:
  - source: /mobile/src/main/res/values/strings.xml
    translation: /mobile/src/main/res/values-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        pt-BR: pt-rBR
