blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://www.openhab.org/docs/apps/android.html
    about: Official documentation
  - name: 📚 Translation feedback
    url: https://crowdin.com/project/openhab-android
    about: Share feedback on translations
