name: Validate Strings

on:
  push:
    branches-ignore:
      - l10n_main
      - dependabot/*
  pull_request:

permissions:
  contents: read

jobs:
  validate-strings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate App Store Strings (play)
        run: python3 assets/store_descriptions/generate_and_validate.py play
      - name: Validate App Store Strings (playBeta)
        run: python3 assets/store_descriptions/generate_and_validate.py playBeta
      - name: Validate App Store Strings (fdroid)
        run: python3 assets/store_descriptions/generate_and_validate.py fdroid
      - name: Validate App Store Strings (fdroidBeta)
        run: python3 assets/store_descriptions/generate_and_validate.py fdroidBeta
      - name: Validate App Strings
        run: python3 ci/validate-app-strings.py
